## Challenge - Joining on multiple tables

/*Write SQL queries to perform the following tasks using the Sakila database:*/
use sakila;
--  List the number of films per category.
SELECT category.category_id, category.name, COUNT(film_category.film_id) AS film_count
FROM category
LEFT JOIN film_category ON category.category_id = film_category.category_id
GROUP BY category.category_id, category.name;

-- 2. Retrieve the store ID, city, and country for each store.

select store.store_id, city.city, country
from store
join address
on store.address_id = address.address_id
join city
on address.city_id = city.city_id
join country
on city.country_id = country.country_id ;

-- 3.  Calculate the total revenue generated by each store in dollars.

select store_id, sum(payment.amount) as total_amount_dollars
from payment
join staff
on staff.staff_id = payment.staff_id
group by staff.store_id;

-- 4.  Determine the average running time of films for each category.

SELECT category.name, COUNT(film_category.film_id) AS film_count, avg(length) as lenght
FROM category
LEFT JOIN film_category ON category.category_id = film_category.category_id
join film
on film_category.film_id = film.film_id
GROUP BY category.name;